/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopyfinal;

import java.awt.Font;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Suthar
 */
public class CreateNewYear extends javax.swing.JFrame {
    String IDyear="2020-2020",Syear="01/01/2020",Eyear="01/01/2020";
    String baseuser="";
    String Curr_IDyear;

    /**
     * Creates new form CreateNewYear
     */
    public CreateNewYear(String buser,String Yr) {
        baseuser = buser;
        Curr_IDyear = Yr;
        initComponents();
        isEnd.setVisible(false);
        this.setLocationRelativeTo(null);
        jEnd.setDate(new Date());
        jStart.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStart = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        jStart = new com.toedter.calendar.JDateChooser();
        jEnd = new com.toedter.calendar.JDateChooser();
        isEnd = new java.awt.Checkbox();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 290));
        setPreferredSize(new java.awt.Dimension(700, 300));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        lblStart.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblStart.setText("Starting Date of New Year");

        lblEnd.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblEnd.setText("Ending Date of New Year");

        jStart.setDateFormatString("dd/MM/yyyy");
        jStart.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jStart.setMaxSelectableDate(new java.util.Date(253370748667000L));
        jStart.setPreferredSize(new java.awt.Dimension(170, 25));

        jEnd.setDate(new java.util.Date(1609443067000L));
        jEnd.setDateFormatString("dd/MM/yyyy");
        jEnd.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jEnd.setMinimumSize(new java.awt.Dimension(145, 25));
        jEnd.setPreferredSize(new java.awt.Dimension(170, 25));

        isEnd.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        isEnd.setLabel("Do you want an upper bound?");
        isEnd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                isEndItemStateChanged(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEnd)
                    .addComponent(lblStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 224, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(236, 236, 236)
                .addComponent(btnCreate)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStart))
                .addGap(11, 11, 11)
                .addComponent(isEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCancel))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        lblHeading.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Creating New Year");
        lblHeading.setAlignmentY(0.0F);
        lblHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeading.setPreferredSize(new java.awt.Dimension(109, 25));
        getContentPane().add(lblHeading, java.awt.BorderLayout.PAGE_START);

        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Year ID will be generated in fromat of YYYYMMDD of Starting");
        getContentPane().add(lblInfo, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isEndItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_isEndItemStateChanged
        if(isEnd.getState()){
            lblEnd.setEnabled(true);
            jEnd.setEnabled(true);
            //lblEnd.setVisible(true);
            //jEnd.setVisible(true);
        }else{
            lblEnd.setEnabled(false);
            jEnd.setEnabled(false);
            //lblEnd.setVisible(false);
            //jEnd.setVisible(false);
        }
    }//GEN-LAST:event_isEndItemStateChanged

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        

                     SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
Syear = dateFormat.format(jStart.getDate());
Eyear = dateFormat.format(jEnd.getDate());
String year_id = shortFunction.YearID(Syear, Eyear);
String addYear = baseuser +"/"+ "Years.txt";
if(!DateInBetween.mainn(Syear, Syear, Eyear)){System.out.println("In This trape"); return;}
boolean b1 = shortFunction.isAlready(Syear,Eyear,addYear);
boolean b3 = shortFunction.isYear_ID_Already(year_id,addYear);
System.out.println(b1+"  "+" "+b3);

if(b1||b3){
    JLabel label = new JLabel("These dates are already exist in some year Account");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
}else{
IDyear= year_id;
int yon = JOptionPane.showConfirmDialog(null,"Do you want to Continue ??","Confirmation .......",JOptionPane.OK_OPTION);
       System.out.println(baseuser +"/"+ "Years.txt");

if(yon==0){//YES   
                try {                //set party account to party.txt

                   PrintWriter out = new PrintWriter(new OutputStreamWriter(new FileOutputStream(baseuser +"/"+ "Years.txt",true), "UTF-8"));
                    out.println(year_id+","+Syear+","+Eyear);
                    out.close();
                } catch (IOException ex) {
                    JLabel label = new JLabel("Years.txt Problem !!! Error00071");
                    label.setFont(new Font("Arial", Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
                }
                // We are calling function whic will do erverything 
                if(shortFunction.YearSetupWhileCreating(baseuser,year_id,Syear,Eyear,Curr_IDyear)){
                        JLabel label = new JLabel("We have Successfully Create a new Finacical year with all update of previous datas");
                        label.setFont(new Font("Arial", Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null,label,"ERROR",JOptionPane.WARNING_MESSAGE);
                }
    this.dispose();
   
}
}
    

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewYear("D:/Shopy/Shopy/2023","20210628-20210630").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private java.awt.Checkbox isEnd;
    private com.toedter.calendar.JDateChooser jEnd;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jStart;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblStart;
    // End of variables declaration//GEN-END:variables
}
