/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopyfinal;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Suthar
 */
public class Item_To_Order extends javax.swing.JFrame {

    /**
     * Creates new form ItemxOrder
     */
    String baseadd, logo, user, ITMadd, lang = "English";
    String IDyear = "2020-2020", Syear = "01/01/2020", Eyear = "01/01/2020";

    public Item_To_Order(String base, String golo, String idy, String sy, String ey) {
        baseadd = base;
        logo = golo;
        IDyear = idy;
        Syear = sy;
        Eyear = ey;
        try {
            user = ShortFunction.GetLine(baseadd + "/Cuser.txt", 2);
        } catch (IOException ex) {
            JLabel label = new JLabel("Current user !!! Error0003");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.WARNING_MESSAGE);

        }
        ITMadd = baseadd + "/" + user + "/" + IDyear + "/item";
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, 900, (int) dim.getHeight() - 50);
        this.setLocationRelativeTo(null);
        try {
            this.setIconImage(ImageIO.read(new File(logo)));
        } catch (IOException ex) {
            JLabel label = new JLabel("Logo Problem !!! Error0001");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.WARNING_MESSAGE);

        }
        try {
            lang = ShortFunction.GetLine(baseadd + "/" + user + "/conf.txt", 1);
            System.out.println(lang);
        } catch (IOException ex) {
            JLabel label = new JLabel("Configuration Error !!! Error0003");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        if (lang.compareToIgnoreCase("English") != 0) {

            up.setText("ऊपर की ओर");
            dwn.setText("नीचे की ओर");
            close.setText("बंद करे");
            save.setText("कन्फर्म");
        }

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Scanner read;
        try {
            read = new Scanner(new File(ITMadd + "/item.txt"), "UTF-8");
            read.useDelimiter("\\n");

            String code, Ename, Hname, rate;
            while (read.hasNext()) {

                //TextIO.put(read.hasNext());
                String Pacc = new String(read.nextLine());
                Scanner inread;
                try {
                    inread = new Scanner(new File(ITMadd + "/" + Pacc + "/profile.txt"), "UTF-8");
                    inread.useDelimiter("\\n");
                    code = inread.nextLine();
                    Ename = inread.nextLine();
                    Hname = inread.nextLine();
                    rate = inread.nextLine();

                    model.addRow(new Object[]{code, Ename, Hname, rate});
                    //TextIO.putln(i);
                    inread.close();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Item_To_Order.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            read.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Item_To_Order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        up = new javax.swing.JButton();
        dwn = new javax.swing.JButton();
        close = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        src = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item List Arrangment");

        table.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name(in English)", "Name(in Hindi)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(20);
        jScrollPane1.setViewportView(table);

        up.setText("Move Up");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        dwn.setText("Move Down");
        dwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwnActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 22)); // NOI18N
        jLabel1.setText("Arrange According to your preference");

        src.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srcKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dwn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(up, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(dwn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        moveRowBy(-1);
    }//GEN-LAST:event_upActionPerformed
    private void moveRowBy(int by) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int[] rows = table.getSelectedRows();
        int destination = rows[0] + by;
        int rowCount = model.getRowCount();

        if (destination < 0 || destination >= rowCount) {
            return;
        }

        model.moveRow(rows[0], rows[rows.length - 1], destination);
        table.setRowSelectionInterval(rows[0] + by, rows[rows.length - 1] + by);
    }
    private void dwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwnActionPerformed
        moveRowBy(1);
    }//GEN-LAST:event_dwnActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
//System.out.println(table.getSelectedRow());
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String scode;
        try {
            PrintWriter out;
            out = new PrintWriter(new OutputStreamWriter(new FileOutputStream(ITMadd + "/item.txt"), "UTF-8"));
            for (int i = 0; i < table.getRowCount(); ++i) {
                Object o;
                o = table.getValueAt(i, 0);
                scode = String.valueOf(o);
                System.out.println(scode);
                out.println(scode);
            }
            out.close();
        } catch (IOException ex) {
            JLabel label = new JLabel("Item item. Error !!! Error0015");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    private void srcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srcKeyReleased
        final DefaultTableModel model = (DefaultTableModel) table.getModel();
        final TableModel tm = table.getModel();
        int t = table.getRowCount();

//table.scrollRectToVisible(null);
        //table.clearSelection();
        //System.out.println("RowCount:"+t);
        String tb;
        int i = 0;
        tb = src.getText();

        //top.setText("1"+tb);
        if (!tb.isEmpty()) {
            int k = evt.getKeyCode();
            if (k == 10) {
                i = table.getSelectedRow();
                //System.out.println("Eneter is Pressed::"+i);
                for (++i; i < t; ++i) {
                    //System.out.println("i="+i);
                    //tb=src.getText();
                    //top.setText("3"+tb);
                    String n = (String) tm.getValueAt(i, 0);
                    n = n.toUpperCase();
                    tb = tb.toUpperCase();
                    //System.out.println("tb="+tb+"   n="+n);
                    if (n.contains(tb)) {
                        //System.out.println("yes:"+tb+":::"+i);
                        table.setRowSelectionInterval(i, i);
                        table.getSelectionModel().setSelectionInterval(i, i);
                        table.scrollRectToVisible(new Rectangle(table.getCellRect(i + 5, 0, true)));
                        break;
                        //table.selectAll();
                    } else {
                        String m = (String) tm.getValueAt(i, 1);
                        m = m.toUpperCase();
                        if (m.contains(tb)) {       //code
                            table.setRowSelectionInterval(i, i);
                            table.getSelectionModel().setSelectionInterval(i, i);
                            table.scrollRectToVisible(new Rectangle(table.getCellRect(i + 5, 0, true)));
                            break;
                        } else {
                            String c = (String) tm.getValueAt(i, 2);
                            c = c.toUpperCase();
                            if (c.contains(tb)) {       //mobile no
                                table.setRowSelectionInterval(i, i);
                                table.getSelectionModel().setSelectionInterval(i, i);
                                table.scrollRectToVisible(new Rectangle(table.getCellRect(i + 5, 0, true)));
                                break;
                            } else {

                                table.clearSelection();
                                //System.out.println("nulli:"+table.getSelectedRow());
                                //src.requestFocus();
                                //table.setRowSelectionInterval(3, 3);

                            }
                        }
                    }

                }
                if (i == t) {
                    table.setRowSelectionInterval(0, 0);
                    table.getSelectionModel().setSelectionInterval(0, 0);
                    table.scrollRectToVisible(new Rectangle(table.getCellRect(0, 0, true)));
                    table.clearSelection();
                }
            } else {
                table.setRowSelectionInterval(0, 0);
                table.getSelectionModel().setSelectionInterval(0, 0);
                table.scrollRectToVisible(new Rectangle(table.getCellRect(0, 0, true)));
                table.clearSelection();
                //tb=src.getText();
                //top.setText("2"+tb);
                i = table.getSelectedRow();
                for (++i; i < t; ++i) {
                    //tb=src.getText();
                    //top.setText("3"+i);
                    String n = (String) tm.getValueAt(i, 0);
                    n = n.toUpperCase();
                    tb = tb.toUpperCase();
                    //System.out.println("tb="+tb+"   n="+n);
                    if (n.contains(tb)) {
                        //System.out.println("yes:"+tb+":::"+i);
                        table.setRowSelectionInterval(i, i);
                        table.getSelectionModel().setSelectionInterval(i, i);
                        table.scrollRectToVisible(new Rectangle(table.getCellRect(i + 5, 0, true)));
                        break;
                        //table.selectAll();
                    } else {
                        String m = (String) tm.getValueAt(i, 1);
                        m = m.toUpperCase();
                        if (m.contains(tb)) {       //code
                            table.setRowSelectionInterval(i, i);
                            table.getSelectionModel().setSelectionInterval(i, i);
                            table.scrollRectToVisible(new Rectangle(table.getCellRect(i + 5, 0, true)));
                            break;
                        } else {
                            String c = (String) tm.getValueAt(i, 2);
                            c = c.toUpperCase();
                            if (c.contains(tb)) {       //mobile no
                                table.setRowSelectionInterval(i, i);
                                table.getSelectionModel().setSelectionInterval(i, i);
                                table.scrollRectToVisible(new Rectangle(table.getCellRect(i + 5, 0, true)));
                                break;
                            } else {
                                table.clearSelection();
                                //System.out.println("nulli:"+table.getSelectedRow());
                                //src.requestFocus();
                                //table.setRowSelectionInterval(3, 3);
                            }
                        }
                    }

                }
                if (i == t) {
                    table.setRowSelectionInterval(0, 0);
                    table.getSelectionModel().setSelectionInterval(0, 0);
                    table.scrollRectToVisible(new Rectangle(table.getCellRect(0, 0, true)));
                    table.clearSelection();
                }
            }
        }
    }//GEN-LAST:event_srcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item_To_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item_To_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item_To_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item_To_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Item_To_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton dwn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JTextField src;
    private javax.swing.JTable table;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
