/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopyfinal;

import javax.swing.Timer;

/**
 *
 * @author Suthar
 */
public class MessageOnTimeOfSuccess extends javax.swing.JFrame {

    /**
     * Creates new form MessageOnTimeOfSuccess
     */
    //int tm=500;
    private static final int TIMER_DELAY = 1500;
    private Timer timer;

    //int sx=500,sy=440;String msg="Successful !!";

    public MessageOnTimeOfSuccess(String msg) {
        initComponents();
        this.setBounds(0, 0, 531, 140);
        //this.setUndecorated(true);
        this.setLocationRelativeTo(null);
        msgp.setText(msg);
        //timer.restart(); 
        timer = new Timer(TIMER_DELAY, e -> {
                //System.out.println("Current Time is: " + new Date(System.currentTimeMillis()));

            if (true) {
                System.out.println("BRESKED");
                timer.setRepeats(false);
                this.dispose();
            }

        });

        timer.restart();
                 //timer.stop();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        msgp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("  Notification ...");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 240, 40));
        setUndecorated(true);
        getContentPane().setLayout(null);

        msgp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        msgp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ezgif.com-resize (1).gif"))); // NOI18N
        msgp.setText("Customer added successfully ");
        getContentPane().add(msgp);
        msgp.setBounds(40, 20, 480, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Green1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 510, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void mainn(String m) {

        new MessageOnTimeOfSuccess(m).setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageOnTimeOfSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageOnTimeOfSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageOnTimeOfSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageOnTimeOfSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new MessageOnTimeOfSuccess("CUstomer ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel msgp;
    // End of variables declaration//GEN-END:variables
}
