/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopyfinal;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Suthar
 */
public class User_Configuration extends javax.swing.JFrame {

    /**
     * Creates new form User_Configuration
     */
    String baseadd, user;

    public User_Configuration(String ba, String usr) {
        initComponents();
        this.setLocationRelativeTo(null);
        baseadd = ba;
        user = usr;
        langlist.setSelectedIndex(0);
        try {
            Gmsg.setText(ShortFunction.GetLine(baseadd + "/" + user + "/conf.txt", 2));
            DirLoc.setText(ShortFunction.GetLine(baseadd + "/" + user + "/conf.txt", 3));
            Autobkup.setState(Boolean.valueOf(ShortFunction.GetLine(baseadd + "/" + user + "/conf.txt", 4)));
        } catch (IOException ex) {
            JLabel label = new JLabel("Something Wrong With the configuration");
            label.setFont(new Font("Arial", Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.WARNING_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        langlist = new javax.swing.JComboBox();
        hdlbl1 = new javax.swing.JLabel();
        Gmsg = new javax.swing.JTextField();
        DirLoc = new javax.swing.JTextField();
        hdlbl = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        save = new javax.swing.JButton();
        Autobkup = new java.awt.Checkbox();
        vhdlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("User Configuration");
        setAlwaysOnTop(true);

        lbl1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lbl1.setText("Select Language :");

        langlist.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        langlist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "हिन्दी" }));

        hdlbl1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        hdlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hdlbl1.setText(": Greeting Message :");

        Gmsg.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        DirLoc.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        hdlbl.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        hdlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hdlbl.setText(": Backup Address :");

        close.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveKeyPressed(evt);
            }
        });

        Autobkup.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Autobkup.setLabel(": Auto Backup");

        vhdlbl.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        vhdlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vhdlbl.setText("Configuration Setup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(langlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hdlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Autobkup, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DirLoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vhdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vhdlbl)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(langlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(hdlbl1)
                .addGap(29, 29, 29)
                .addComponent(Gmsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(hdlbl)
                .addGap(39, 39, 39)
                .addComponent(DirLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(Autobkup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(close))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        this.setAlwaysOnTop(false);
        int yon = JOptionPane.showConfirmDialog(null, "Do you want to Continue ??", "Confirmation .......", JOptionPane.OK_OPTION);

        if (yon == 0) {//YES
            System.out.println("YES");
            try {
                //Replace Line 2

                ShortFunction.ReplaceLineWN(baseadd + "/" + user, "conf.txt", 1, (String) langlist.getSelectedItem());
                ShortFunction.ReplaceLineWN(baseadd + "/" + user, "conf.txt", 2, Gmsg.getText());
                ShortFunction.ReplaceLineWN(baseadd + "/" + user, "conf.txt", 3, DirLoc.getText());
                ShortFunction.ReplaceLineWN(baseadd + "/" + user, "conf.txt", 4, String.valueOf(Autobkup.getState()));
                JLabel label = new JLabel("Configuration Saved Succefully");
                label.setFont(new Font("Arial", Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "Notification ", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (IOException ex) {
                JLabel label = new JLabel("Not Able Save configuration !");
                label.setFont(new Font("Arial", Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            this.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void saveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            save.doClick();
        }
    }//GEN-LAST:event_saveKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new User_Configuration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox Autobkup;
    private javax.swing.JTextField DirLoc;
    private javax.swing.JTextField Gmsg;
    private javax.swing.JButton close;
    private javax.swing.JLabel hdlbl;
    private javax.swing.JLabel hdlbl1;
    private javax.swing.JComboBox langlist;
    private javax.swing.JLabel lbl1;
    private javax.swing.JButton save;
    private javax.swing.JLabel vhdlbl;
    // End of variables declaration//GEN-END:variables
}
